name: Claude API 테스트 워크플로우

on:
  workflow_dispatch: # 수동 실행용 트리거

jobs:
  call-claude:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Claude 호출 (Anthropic API)
        run: |
          curl https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d '{
              "model": "claude-3-opus-20240229",
              "max_tokens": 100,
              "messages": [{"role": "user", "content": "Hello Claude!"}]
            }'
