name: Claude Code Action (Manual Setup)

on:
  workflow_dispatch:

jobs:
  call-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Claude API manually
        run: |
          curl https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d '{
              "model": "claude-3-opus-20240229",
              "max_tokens": 100,
              "messages": [{"role": "user", "content": "What is Claude?"}]
            }'
